server {
    listen 80;
    server_name localhost;

    # Compresión GZIP habilitada para el Frontend
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # 1. Host App (El cascarón principal)
    location / {
        root /usr/share/nginx/html/host;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Opciones avanzadas de caché para assets estáticos
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
            expires 6M;
            access_log off;
            add_header Cache-Control "public";
        }
    }

    # 2. Remote MFE: Bandeja unificada de tareas
    location /inbox-remote/ {
        alias /usr/share/nginx/html/inbox/;
        
        # Exigencia Module Federation: Evitar colisiones de CORS en fetch de remotes
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
            expires 6M;
            access_log off;
        }
    }

    # 3. Remote MFE: Diseñador de Reglas de Negocio
    location /admin-remote/ {
        alias /usr/share/nginx/html/admin/;
        
        # Exigencia Module Federation
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, OPTIONS";
        
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
            expires 6M;
            access_log off;
        }
    }
}
