version: '3.8'

services:
  # 1. Base de Datos Relacional y Vectorial (PostgreSQL + PgVector)
  # Necesaria para guardar transacciones BPM y Vectores del modelo RAG Racional de la IA.
  ibpms-postgres:
    image: ankane/pgvector:latest
    container_name: ibpms-postgres-uat
    restart: unless-stopped
    environment:
      POSTGRES_USER: ibpms_user
      POSTGRES_PASSWORD: ibpms_password
      POSTGRES_DB: ibpms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ibpms_user -d ibpms_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Gestor de Colas de Mensajería (RabbitMQ)
  # Necesario para procesar eventos asíncronos (Correos, Webhooks, Reintentos MLOps nocturnos).
  ibpms-rabbitmq:
    image: rabbitmq:3-management
    container_name: ibpms-rabbitmq-uat
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # Puerto estándar AMQP para el Backend Spring Boot
      - "15672:15672" # Interfaz gráfica de administración web (http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Base de Datos en Memoria (Redis Cache)
  # Necesario para Caching de catálogos paramétricos y Locks Distribuidos de tareas seguras del BPM.
  ibpms-redis:
    image: redis:7-alpine
    container_name: ibpms-redis-uat
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. Backend Core (Spring Boot - Dev Mode)
  # Container agnóstico para Hot-Reloading de código sin requerir Maven en el Host
  ibpms-core:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: ibpms-core-dev
    restart: unless-stopped
    working_dir: /app/ibpms-core
    environment:
      - POSTGRES_HOST=ibpms-postgres
      - RABBITMQ_HOST=ibpms-rabbitmq
      - REDIS_HOST=ibpms-redis
    volumes:
      - ./backend:/app
      - maven_data:/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run -DskipTests
    depends_on:
      ibpms-postgres:
        condition: service_healthy
      ibpms-rabbitmq:
        condition: service_healthy
      ibpms-redis:
        condition: service_healthy

volumes:
  # Volúmenes persistentes para que los datos no se pierdan al apagar la computadora / detener Docker
  postgres_data:
  rabbitmq_data:
  redis_data:
  maven_data:
