$env:POSTGRES_HOST="localhost"
$env:POSTGRES_PORT="5432"
$env:POSTGRES_DB="ibpms_db"
$env:POSTGRES_USER="ibpms_user"
$env:POSTGRES_PASSWORD="ibpms_password"
$env:RABBITMQ_HOST="localhost"
$env:RABBITMQ_PORT="5672"
$env:RABBITMQ_USER="guest"
$env:RABBITMQ_PASSWORD="guest"
$env:REDIS_HOST="localhost"
$env:REDIS_PORT="6379"
$env:JWT_SECRET="changeme-this-must-be-at-least-32-chars-for-hs256-signature!!"

& mvn spring-boot:run "-Dmaven.test.skip=true"
