spring:
  config:
    activate:
      on-profile: uat

  # Configuración de Base de Datos PostgreSQL
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ibpms_db}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:ibpms_user}
    password: ${POSTGRES_PASSWORD:ibpms_password}

  # Inicialización de Esquemas
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Crea tablas automáticamente basándose en las entidades JPA
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # Consola H2 para inspección manual (Opcional, útil para debugear)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

# Camunda Configuration
camunda:
  bpm:
    client:
      base-url: "http://localhost:8080/engine-rest"
    database:
      type: postgres
      schema-update: true
    generic-properties:
      properties:
        history: audit

# Deshabilitar brokers si no están montados localmente (RabbitMQ, Redis) para evitar cuelgues al iniciar
  redis:
    repositories:
      enabled: false

# Configuración Mock para Storage en UAT
app:
  azure:
    storage:
      connection-string: "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;EndpointSuffix=core.windows.net"
      container-name: "ibpms-docs"

# Configuraciones Dummy de Seguridad JWT para dev/uat
ibpms:
  security:
    jwt:
      secret: "UAT_SUPER_SECRET_KEY_THAT_IS_VERY_LONG_AND_SECURE_982374982374892374"
      expiration-ms: 86400000

management:
  health:
    camunda:
      enabled: false

logging:
  level:
    com.ibpms: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
